Firma.Intranet/Controllers/JachtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Firma.Data.Data;
using Firma.Data.Data.Flota;

namespace Firma.Intranet.Controllers
{
    public class JachtController : Controller
    {
        private readonly FirmaContext _context;

        public JachtController(FirmaContext context)
        {
            _context = context;
        }

        // GET: Jacht
        public async Task<IActionResult> Index()
        {
            var jachty = await _context.Jachty
                .Include(j => j.KategoriaJachtu)
                .Include(j => j.Port)
                .ToListAsync();

            return View(jachty);
        }


        // GET: Jacht/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var jacht = await _context.Jachty
                .Include(j => j.KategoriaJachtu)
                .Include(j => j.Port)
                .FirstOrDefaultAsync(m => m.IdJachtu == id);

            if (jacht == null) return NotFound();

            return View(jacht);
        }

        // GET: Jacht/Create
        public IActionResult Create()
        {
            ViewData["IdKategorii"] = new SelectList(_context.KategorieJachtow, "IdKategorii", "Nazwa");
            ViewData["IdPortu"] = new SelectList(_context.Porty, "IdPortu", "Nazwa");
            return View();
        }

        // POST: Jacht/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdJachtu,Nazwa,RokBudowy,CenaZaDzien,Opis,IdKategorii,IdPortu")] Jacht jacht)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jacht);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdKategorii"] = new SelectList(_context.KategorieJachtow, "IdKategorii", "Nazwa", jacht.IdKategorii);
            ViewData["IdPortu"] = new SelectList(_context.Porty, "IdPortu", "Nazwa", jacht.IdPortu);
            return View(jacht);
        }

        // GET: Jacht/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var jacht = await _context.Jachty.FindAsync(id);
            if (jacht == null) return NotFound();
            
            ViewData["IdKategorii"] = new SelectList(_context.KategorieJachtow, "IdKategorii", "Nazwa", jacht.IdKategorii);
            ViewData["IdPortu"] = new SelectList(_context.Porty, "IdPortu", "Nazwa", jacht.IdPortu);
            return View(jacht);
        }

        // POST: Jacht/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdJachtu,Nazwa,RokBudowy,CenaZaDzien,Opis,IdKategorii,IdPortu")] Jacht jacht)
        {
            if (id != jacht.IdJachtu) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jacht);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JachtExists(jacht.IdJachtu)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdKategorii"] = new SelectList(_context.KategorieJachtow, "IdKategorii", "Nazwa", jacht.IdKategorii);
            ViewData["IdPortu"] = new SelectList(_context.Porty, "IdPortu", "Nazwa", jacht.IdPortu);
            return View(jacht);
        }

        // GET: Jacht/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var jacht = await _context.Jachty
                .Include(j => j.KategoriaJachtu)
                .Include(j => j.Port)
                .FirstOrDefaultAsync(m => m.IdJachtu == id);

            if (jacht == null) return NotFound();

            return View(jacht);
        }

        // POST: Jacht/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jacht = await _context.Jachty.FindAsync(id);
            if (jacht != null)
            {
                _context.Jachty.Remove(jacht);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool JachtExists(int id)
        {
            return _context.Jachty.Any(e => e.IdJachtu == id);
        }
    }
}

Firma.Intranet/Controllers/KlientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Firma.Data.Data;
using Firma.Data.Data.Rezerwacje;

namespace Firma.Intranet.Controllers
{
    public class KlientController : Controller
    {
        private readonly FirmaContext _context;

        public KlientController(FirmaContext context)
        {
            _context = context;
        }

        // GET: Klient
        public async Task<IActionResult> Index()
        {
            return View(await _context.Klienci.ToListAsync());
        }

        // GET: Klient/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klient = await _context.Klienci
                .FirstOrDefaultAsync(m => m.IdKlienta == id);
            if (klient == null)
            {
                return NotFound();
            }

            return View(klient);
        }

        // GET: Klient/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Klient/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdKlienta,Imie,Nazwisko,Email")] Klient klient)
        {
            if (ModelState.IsValid)
            {
                _context.Add(klient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(klient);
        }

        // GET: Klient/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klient = await _context.Klienci.FindAsync(id);
            if (klient == null)
            {
                return NotFound();
            }
            return View(klient);
        }

        // POST: Klient/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdKlienta,Imie,Nazwisko,Email")] Klient klient)
        {
            if (id != klient.IdKlienta)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(klient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KlientExists(klient.IdKlienta))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(klient);
        }

        // GET: Klient/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klient = await _context.Klienci
                .FirstOrDefaultAsync(m => m.IdKlienta == id);
            if (klient == null)
            {
                return NotFound();
            }

            return View(klient);
        }

        // POST: Klient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var klient = await _context.Klienci.FindAsync(id);
            if (klient != null)
            {
                _context.Klienci.Remove(klient);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KlientExists(int id)
        {
            return _context.Klienci.Any(e => e.IdKlienta == id);
        }
    }
}

Firma.Intranet/Controllers/RezerwacjaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Firma.Data.Data;
using Firma.Data.Data.Rezerwacje;

namespace Firma.Intranet.Controllers
{
    public class RezerwacjaController : Controller
    {
        private readonly FirmaContext _context;

        public RezerwacjaController(FirmaContext context)
        {
            _context = context;
        }

        // GET: Rezerwacja
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rezerwacje.ToListAsync());
        }

        // GET: Rezerwacja/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rezerwacja = await _context.Rezerwacje
                .FirstOrDefaultAsync(m => m.IdRezerwacji == id);
            if (rezerwacja == null)
            {
                return NotFound();
            }

            return View(rezerwacja);
        }

        // GET: Rezerwacja/Create
        public IActionResult Create()
        {
            ViewData["IdJachtu"] = new SelectList(_context.Jachty, "IdJachtu", "Nazwa");
            ViewData["IdKlienta"] = new SelectList(_context.Klienci, "IdKlienta", "Email");

            return View();
        }

        // POST: Rezerwacja/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRezerwacji,DataOd,DataDo,IdJachtu,IdKlienta")] Rezerwacja rezerwacja)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rezerwacja);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdJachtu"] = new SelectList(_context.Jachty, "IdJachtu", "Nazwa");
            ViewData["IdKlienta"] = new SelectList(_context.Klienci, "IdKlienta", "Email");

            return View(rezerwacja);
        }

        // GET: Rezerwacja/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rezerwacja = await _context.Rezerwacje.FindAsync(id);
            if (rezerwacja == null)
            {
                return NotFound();
            }
            ViewData["IdJachtu"] = new SelectList(_context.Jachty, "IdJachtu", "Nazwa", rezerwacja.IdJachtu);
            ViewData["IdKlienta"] = new SelectList(_context.Klienci, "IdKlienta", "Email", rezerwacja.IdKlienta);

            return View(rezerwacja);
        }

        // POST: Rezerwacja/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRezerwacji,DataOd,DataDo,IdJachtu,IdKlienta")] Rezerwacja rezerwacja)
        {
            if (id != rezerwacja.IdRezerwacji)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rezerwacja);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RezerwacjaExists(rezerwacja.IdRezerwacji))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rezerwacja);
        }

        // GET: Rezerwacja/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rezerwacja = await _context.Rezerwacje
                .FirstOrDefaultAsync(m => m.IdRezerwacji == id);
            if (rezerwacja == null)
            {
                return NotFound();
            }

            return View(rezerwacja);
        }

        // POST: Rezerwacja/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rezerwacja = await _context.Rezerwacje.FindAsync(id);
            if (rezerwacja != null)
            {
                _context.Rezerwacje.Remove(rezerwacja);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RezerwacjaExists(int id)
        {
            return _context.Rezerwacje.Any(e => e.IdRezerwacji == id);
        }
    }
}

Firma.Intranet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Panel startowy";
}

<div class="alert alert-info d-flex align-items-center" role="alert">
    <i class="bi bi-info-circle-fill me-2"></i>
    Witaj w panelu administracyjnym Morski Czarter!
</div>

<!-- Sekcja Statystyki -->
<h4 class="mb-3">Statystyki</h4>
<div class="row g-4 mb-5">
    <!-- Strony -->
    <div class="col-md-3">
        <div class="card text-center shadow-sm">
            <div class="card-body">
                <i class="bi bi-file-earmark-text-fill display-4 text-success mb-2"></i>
                <h5 class="card-title">@ViewBag.LiczbaStron</h5>
                <p class="card-text text-muted">Liczba stron</p>
            </div>
        </div>
    </div>
    <!-- Zapytania -->
    <div class="col-md-3">
        <div class="card text-center shadow-sm">
            <div class="card-body">
                <i class="bi bi-inbox-fill display-4 text-danger mb-2"></i>
                <h5 class="card-title">@ViewBag.LiczbaZapytan</h5>
                <p class="card-text text-muted">Ilość zapytań od klientów</p>
            </div>
        </div>
    </div>
    <!-- Rezerwacje -->
    <div class="col-md-3">
        <div class="card text-center shadow-sm">
            <div class="card-body">
                <i class="bi bi-calendar-check-fill display-4 text-warning mb-2"></i>
                <h5 class="card-title">@ViewBag.LiczbaRezerwacji</h5>
                <p class="card-text text-muted">Liczba rezerwacji</p>
            </div>
        </div>
    </div>
    <!-- Klienci -->
    <div class="col-md-3">
        <div class="card text-center shadow-sm">
            <div class="card-body">
                <i class="bi bi-person-fill display-4 text-primary mb-2"></i>
                <h5 class="card-title">@ViewBag.LiczbaKlientow</h5>
                <p class="card-text text-muted">Ilość klientów</p>
            </div>
        </div>
    </div>
</div>


<!-- Sekcja Szybki dostęp -->
<h4 class="mb-3">Szybki dostęp</h4>
<div class="row g-4 mb-5">
    <div class="col-md-3">
        <div class="card shadow-sm h-100 text-center">
            <div class="card-body d-flex flex-column justify-content-between">
                <i class="bi bi-rocket display-3 text-primary mb-3"></i>
                <h5 class="card-title">Zarządzaj jachtami</h5>
                <p class="card-text">Dodawaj, edytuj i usuwaj jednostki pływające z oferty.</p>
                <a asp-controller="Jacht" asp-action="Index" class="btn btn-outline-primary mt-3">Przejdź</a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card shadow-sm h-100 text-center">
            <div class="card-body d-flex flex-column justify-content-between">
                <i class="bi bi-people-fill display-3 text-dark mb-3"></i>
                <h5 class="card-title">Baza klientów</h5>
                <p class="card-text">Lista wszystkich zarejestrowanych klientów.</p>
                <a asp-controller="Klient" asp-action="Index" class="btn btn-outline-dark mt-3">Przejdź</a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card shadow-sm h-100 text-center">
            <div class="card-body d-flex flex-column justify-content-between">
                <i class="bi bi-calendar-event-fill display-3 text-warning mb-3"></i>
                <h5 class="card-title">Rezerwacje</h5>
                <p class="card-text">Podgląd aktualnych i archiwalnych rezerwacji.</p>
                <a asp-controller="Rezerwacja" asp-action="Index" class="btn btn-outline-warning mt-3">Przejdź</a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card shadow-sm h-100 text-center">
            <div class="card-body d-flex flex-column justify-content-between">
                <i class="bi bi-images display-3 text-secondary mb-3"></i>
                <h5 class="card-title">Galeria jachtów</h5>
                <p class="card-text">Zarządzaj zdjęciami przypisanymi do jachtów.</p>
                <a asp-controller="ZdjecieJachtu" asp-action="Index" class="btn btn-outline-secondary mt-3">Przejdź</a>
            </div>
        </div>
    </div>
</div>

Firma.Intranet/Views/Home/Jachty.cshtml
@{
    ViewData["Title"] = "Zarządzanie jachtami";
}

<h2 class="mb-4 text-center">Zarządzanie jachtami</h2>
<p class="text-muted text-center mb-4">
    Poniżej znajduje się zestawienie wszystkich jednostek dostępnych w ofercie.
</p>

<div class="mb-3 text-end">
    <a class="btn btn-success">
        <i class="bi bi-plus-circle me-1"></i> Dodaj
    </a>
</div>

<table class="table table-bordered table-striped align-middle">
    <thead class="table-dark text-center">
        <tr>
            <th>Nazwa jachtu</th>
            <th>Kategoria</th>
            <th>Status</th>
            <th>Akcje</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Posejdon 500</td>
            <td>Motorowodny</td>
            <td class="text-success">Aktywny</td>
            <td class="text-center">
                <a class="btn btn-sm btn-primary"><i class="bi bi-eye"></i> Szczegóły</a>
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Rodos Explorer</td>
            <td>Motorowodny</td>
            <td class="text-success">Aktywny</td>
            <td class="text-center">
                <a class="btn btn-sm btn-primary"><i class="bi bi-eye"></i> Szczegóły</a>
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Lefkada Sport 320</td>
            <td>Motorowodny</td>
            <td class="text-success">Aktywny</td>
            <td class="text-center">
                <a class="btn btn-sm btn-primary"><i class="bi bi-eye"></i> Szczegóły</a>
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Atena Speedster</td>
            <td>Motorowodny</td>
            <td class="text-success">Aktywny</td>
            <td class="text-center">
                <a class="btn btn-sm btn-primary"><i class="bi bi-eye"></i> Szczegóły</a>
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Zakynthos Turbo</td>
            <td>Motorowodny</td>
            <td class="text-danger">Nieaktywny</td>
            <td class="text-center">
                <a class="btn btn-sm btn-primary"><i class="bi bi-eye"></i> Szczegóły</a>
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Greco Cruiser</td>
            <td>Motorowodny</td>
            <td class="text-success">Aktywny</td>
            <td class="text-center">
                <a class="btn btn-sm btn-primary"><i class="bi bi-eye"></i> Szczegóły</a>
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Athena 400</td>
            <td>Katamaran</td>
            <td class="text-success">Aktywny</td>
            <td class="text-center">
                <a class="btn btn-sm btn-primary"><i class="bi bi-eye"></i> Szczegóły</a>
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Santorini Cat</td>
            <td>Katamaran</td>
            <td class="text-warning">W trakcie rezerwacji</td>
            <td class="text-center">
                <a class="btn btn-sm btn-primary"><i class="bi bi-eye"></i> Szczegóły</a>
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
    </tbody>
</table>

Firma.Intranet/Views/Home/Strony.cshtml
@{
    ViewData["Title"] = "Strony portalu";
}

<h2 class="mb-4 text-center">Strony portalu</h2>
<p class="text-muted text-center mb-4">
    Zarządzaj treściami widocznymi w aplikacji klienta – Morski Czarter.
</p>

<table class="table table-bordered table-hover align-middle">
    <thead class="table-dark text-center">
        <tr>
            <th>Tytuł strony</th>
            <th>Widoczność</th>
            <th>Data modyfikacji</th>
            <th>Akcje</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>O nas</td>
            <td><span class="badge bg-success">Widoczna</span></td>
            <td>2025-04-10</td>
            <td class="text-center">
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Oferta</td>
            <td><span class="badge bg-success">Widoczna</span></td>
            <td>2025-04-09</td>
            <td class="text-center">
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
        <tr>
            <td>Kontakt</td>
            <td><span class="badge bg-secondary">Ukryta</span></td>
            <td>2025-03-28</td>
            <td class="text-center">
                <a class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i> Edytuj</a>
                <a class="btn btn-sm btn-danger"><i class="bi bi-trash"></i> Usuń</a>
            </td>
        </tr>
    </tbody>
</table>

Firma.Intranet/Views/Home/Zapytania.cshtml
@{
    ViewData["Title"] = "Zapytania od klientów";
}

<h2 class="mb-4 text-center">Zapytania od klientów</h2>
<p class="text-muted text-center mb-4">
    Poniżej znajduje się zestawienie wiadomości przesłanych z formularza kontaktowego.
</p>

<table class="table table-bordered table-hover align-middle">
    <thead class="table-dark text-center">
        <tr>
            <th>Imię i nazwisko</th>
            <th>Email</th>
            <th>Jacht</th>
            <th>Termin</th>
            <th>Wiadomość</th>
            <th>Akcje</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Jan Kowalski</td>
            <td>jan.kowalski@example.com</td>
            <td>Athena 400</td>
            <td>2025-07-01 – 2025-07-10</td>
            <td>Interesuje mnie czarter katamaranu w lipcu. Proszę o kontakt.</td>
            <td class="text-center">
                <a class="btn btn-sm btn-outline-primary"><i class="bi bi-envelope-open"></i> Odpowiedz</a>
            </td>
        </tr>
        <tr>
            <td>Anna Nowak</td>
            <td>anna.nowak@example.com</td>
            <td>Posejdon 500</td>
            <td>2025-08-05 – 2025-08-12</td>
            <td>Czy jacht jest jeszcze dostępny w sierpniu?</td>
            <td class="text-center">
                <a class="btn btn-sm btn-outline-primary"><i class="bi bi-envelope-open"></i> Odpowiedz</a>
            </td>
        </tr>
        <tr>
            <td>Piotr Zieliński</td>
            <td>piotr.z@example.com</td>
            <td>Santorini Cat</td>
            <td>2025-07-18 – 2025-07-25</td>
            <td>Chciałbym zarezerwować katamaran na tydzień. Czy są wolne terminy?</td>
            <td class="text-center">
                <a class="btn btn-sm btn-outline-primary"><i class="bi bi-envelope-open"></i> Odpowiedz</a>
            </td>
        </tr>
    </tbody>
</table>